export const RECEIVE_WEB3_ACCOUNTS = 'RECEIVE_WEB3_ACCOUNTS'
export const ETHER_TRANSFERED = 'ETHER_TRANSFERED'
export const DEBUG_SETTINGS_UPDATED = 'DEBUG_SETTINGS_UPDATED'

export const Constants = {
  RECEIVE_WEB3_ACCOUNTS,
  ETHER_TRANSFERED,
  DEBUG_SETTINGS_UPDATED
}
