export const RECEIVE_FAUCET = 'RECEIVE_FAUCET'
export const RECEIVE_FAUCET_ADDRESSES = 'RECEIVE_FAUCET_ADDRESSES'
export const RECEIVE_FAUCET_EVENT_STORE = 'RECEIVE_FAUCET_EVENT_STORE'
export const FAUCET_READ_MODEL_EVENTS_RECEIVED = 'FAUCET_READ_MODEL_EVENTS_RECEIVED'
export const FAUCET_ACCESS_REQUESTED = 'FAUCET_ACCESS_REQUESTED'
export const FAUCET_ACCESS_GRANTED = 'FAUCET_ACCESS_GRANTED'
export const FAUCET_ACCESS_REVOKED = 'FAUCET_ACCESS_REVOKED'
export const RECEIVE_FAUCET_OBJECTS = 'RECEIVE_FAUCET_OBJECTS'
export const FAUCET_CREATED = 'FAUCET_CREATED'
export const FAUCET_UPDATED = 'FAUCET_UPDATED'
export const SEND_WEI = 'SEND_WEI'
export const DONATE_WEI = 'DONATE_WEI'
export const RECEIVE_WEB3_ACCOUNTS = 'RECEIVE_WEB3_ACCOUNTS'

export const Constants = {
  RECEIVE_FAUCET,
  RECEIVE_FAUCET_ADDRESSES,
  RECEIVE_FAUCET_EVENT_STORE,
  FAUCET_READ_MODEL_EVENTS_RECEIVED,
  FAUCET_ACCESS_REQUESTED,
  FAUCET_ACCESS_GRANTED,
  FAUCET_ACCESS_REVOKED,
  RECEIVE_FAUCET_OBJECTS,
  FAUCET_CREATED,
  FAUCET_UPDATED,
  SEND_WEI,
  DONATE_WEI,
  RECEIVE_WEB3_ACCOUNTS
}
